version: "3.9"
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authdb
    networks:
      - my-network

  eureka-server:
    build:
      context: ./eureka_server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  auth-service:
    build:
      context: ./auth_service
    container_name: auth-service
    ports:
      - "8085:8085"
    depends_on:
      - mariadb
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/authdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network

  user-service:
    build:
      context: ./user_service
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - my-network

  product-service:
    build:
      context: ./product_service
    container_name: product-service
    ports:
      - "5000:5000"
    depends_on:
      - eureka-server
    networks:
      - my-network

  provider-service:
    build:
      context: ./provider_service
    container_name: provider-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - my-network

  order-service:
    build:
      context: ./order_service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    networks:
      - my-network

  inventory-service:
    build:
      context: ./inventory_service
    container_name: inventory-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    networks:
      - my-network

  payment-service:
    build:
      context: ./payment_service
    container_name: payment-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - my-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
# Chạy Docker
# docker-compose up --build

# Đóng Docker
# docker-compose down -v
# docker-compose logs auth-service

# Nếu code có lỗi, chạy lại
# docker compose build --no-cache
# docker compose up

# Build service
# mvn clean package -DskipTests

# Build lại service
# docker compose down --volumes --remove-orphans
# docker compose build --no-cache
# docker compose up

# Xem status
# docker ps

# Nếu có code mới ở sẻvice nào thì
# docker restart auth-service

# Có code mới
# mvn clean package -DskipTests
# docker-compose build inventory-service
# docker-compose up -d inventory-service