name: Build and Deploy MariaDB to Render

on:
  push:
    branches:
      - main
    paths:
      - 'mariadb/**'   # thư mục Dockerfile MariaDB nếu bạn để đó

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build MariaDB image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mariadb-custom:latest ./mariadb

      - name: Push MariaDB image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mariadb-custom:latest

  deploy-to-render:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy MariaDB to Render
        run: |
          curl -X POST https://api.render.com/deploy/<YOUR_MARIADB_SERVICE_ID> \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"image": "${{ secrets.DOCKER_USERNAME }}/mariadb-custom:latest"}'
