name: Deploy Payment Service to Render

on:
  push:
    paths:
      - 'payment_service/**'
      - '.github/workflows/deploy-payment.yml'
    branches:
      - deloy

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Java project
        run: mvn clean package -f ./payment_service/pom.xml -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/payment-service:latest ./payment_service

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/payment-service:latest

  deploy-to-render:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl -X POST "https://api.render.com/deploy/YOUR_PAYMENT_SERVICE_ID?key=${{ secrets.RENDER_API_KEY }}"
