# name: Run Full Docker Compose

# on:
#   push:
#     branches: [deloy]
#   workflow_dispatch:

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v3

#       - name: Run Docker Compose
#         run: docker compose up -d --build

#       - name: Check running containers
#         run: docker ps
name: Run Full Docker Compose

on:
  push:
    branches: [deloy]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Docker Compose
        run: docker compose up -d --build

      - name: Wait for containers to be healthy
        run: |
          # Ví dụ đợi 20s để container khởi động
          sleep 20
          # Kiểm tra trạng thái container (tùy chỉnh tên service nếu có)
          docker ps

      - name: Show logs (optional)
        run: docker compose logs --tail=50
